// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnnumplikxkdkeyxhswz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubnVtcGxpa3hrZGtleXhoc3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzg2MjIsImV4cCI6MjA2Mzg1NDYyMn0.M6yzxYpu_cvJG3apEUzqqPEYzZjgkYusqJ2tuzrxkQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);